---
title: "Demographic Factors"
execute: 
  echo: false
---

```{r}
#| label: setup
#| message: false

library(tidyverse)
library(brms)
library(tidybayes)
library(gtsummary)
library(wesanderson)
library(plotly)
```

```{r}
#| label: import_data

# Brought downloaded CSV file with data into project through terminal. Turned
# CSV file into data frame. Kept only the data that combined all age groups
# together to see the general trend in incidence rates over time.

ms_data <- read_csv("DataFilterExport.csv", show_col_types = FALSE)
ms_data_clean_time <- ms_data |>
  filter(Age == "ALL")
```

```{r}
#| label: create_line_graph

# Created line graph to show trend of MS Incidence Rates in Alberta over time.
# Tried bar graph but decided on line graph so trend was more apparent. Created
# lines for each of the Sex categories to see the effect of Sex on incidence
# rate change over time. Used Wes Anderson Palettes R package for colors in line
# graph. Opted not to add title since it was the same as the page and subtitle
# since key takeaways were listed in paragraph below. Used minimal theme for
# clean look.

ms_line <-
  ms_data_clean_time |>
  ggplot(aes(x = Year, y = `Incidence Rate`, color = Sex)) +
  geom_line(linewidth = 0.75) +
  scale_color_manual(values = wes_palette("Cavalcanti1")[c(4, 1, 5)]) +
  labs(x = "Year", 
       y = "Incidence Rate (per 100 000)", 
       color = "Sex") +
  theme_minimal()

# Used plotly package to make graph interactive. Added caption to provide source
# of data, and adjusted sizing and placement of caption. Displayed line graph.

interactive_line <- 
  ggplotly(ms_line, tooltip = c("Year", "Incidence Rate")) |>
    layout( annotations = list(
      text = "Data from Alberta IHDA",
      x = 1, y = -0.25,
      xref = "paper", yref = "paper",
      showarrow = FALSE,
      font = list(size = 12)), 
      margin = list(b = 100))

interactive_line
```

```{r}
raw_df <- read_csv("ms-conversion-rate.csv", show_col_types = FALSE)

ms_data <- raw_df[-c(274:288) ,] |>
  mutate(Age = `Age (y)`) |>
  mutate(Schooling = `Schooling (y)`) |>
  mutate(Gender = recode(Gender,
                         '1' = "male",
                         '2' = "female")) |>
  mutate(Breastfeeding = recode(Breastfeeding,
                                '1' = "yes",
                                '2' = "no",
                                '3' = "unknown")) |>
  mutate(Varicella = recode(Varicella,
                            '1' = "positive",
                            '2' = "negative",
                            '3' = "unknown")) |>
  mutate(Initial_Symptoms = recode(`initial symptom`,
                                  '1' = "visual",
                                  '2' = "sensory",
                                  '3' = "motor",
                                  '4' = "other",
                                  '5' = "visual  and sensory",
                                  '6' = "visual  and motor",
                                  '7' = "visual  and other",
                                  '8' = "sensory  and motor",
                                  '9' = "sensory  and other",
                                  '10' = "motor  and  other",
                                  '11' = "visual,  sensory and motor",
                                  '12' = "visual, sensory  and other",
                                  '13' = "visual, motor and  other",
                                  '14' = "sensory,  motor and   other",
                                  '15' = "visual,sensory,motor and other")) |>
  mutate(Mono_Poly = recode(`Mono or polysymptomatic`,
                            '1' = "monosymptomatic",
                            '2' = "polysymptomatic",
                            '3' = "unknown")) |>
  mutate(Oligoclonal_Bands = recode(`Oligoclonal bands`,
                                   '0' = "negative",
                                   '1' = "positive",
                                   '2' = "unknown")) |>
  mutate(LLSSEP = recode(LLSSEP,
                        '0' = "negative",
                        '1' = "positive")) |>
  mutate(ULSSEP = recode(ULSSEP,
                        '0' = "negative",
                        '1' = "positive")) |>
  mutate(VEP = recode(VEP,
                      '0' = "negative",
                      '1' = "positive")) |>
  mutate(BAEP = recode(BAEP,
                       '0' = "negative",
                       '1' = "positive")) |>
  mutate(Periventricular_MRI = recode(`Periventricular MRI`,
                                      '0' = "negative",
                                      '1' = "positive")) |>
  mutate(Cortical_MRI = recode(`Cortical MRI`,
                                '0' = "negative",
                                '1' = "positive")) |>
  mutate(Infratentorial_MRI = recode(`Infratentorial MRI`,
                                      '0' = "negative",
                                      '1' = "positive")) |>
  mutate(Spinal_Cord_MRI = recode(`Spinal cord MRI`,
                                  '0' = "negative",
                                  '1' = "positive")) |> 
  mutate(group = recode(group,
                        '1' = "CDMS",
                        '2' = "Non-CDMS")) |>
  select(Patient, 
         Gender, 
         Age, 
         Schooling, 
         Breastfeeding, 
         Varicella,
         Initial_Symptoms,
         Mono_Poly,
         Oligoclonal_Bands,
         LLSSEP,
         ULSSEP,
         VEP,
         BAEP,
         Periventricular_MRI,
         Cortical_MRI,
         Infratentorial_MRI,
         Spinal_Cord_MRI,
         group) |> 
  drop_na()
```

```{r}
#| cache: true
fit_dem <- brm(formula = group ~ Gender,
              data = ms_data,
              family = bernoulli(),
              silent = 2,
              refresh = 0,
              seed = 9)
```

```{r}
tbl_regression(fit_dem)
```

```{r}
#| message: false
ndata <- tibble(Gender = c("male", "female"))

fit_dem |>
  add_epred_draws(newdata = ndata) |>
  ungroup() |>
  ggplot(aes(x = .epred, fill = Gender)) + 
  geom_density(aes(y = after_stat(count/sum(count)))) +
  labs(title = "Posterior Distribution for Probability of Developing MS Based on Sex",
       x = "Expected Probability of Developing MS",
       y = "Probability",
       fill = "Sex") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_fill_manual(values = wes_palette("Royal1")) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_classic()
```
```


