---
title: "Model"
execute: 
  echo: false
---

```{r}
#| label: setup
#| message: false 

library(tidyverse)
library(brms)
library(tidybayes)
library(gtsummary)
```

```{r}
#| label: download_format_data

# Brought downloaded CSV file with data into project through
# terminal. Turned CSV file into data frame.

raw_df <- read_csv("ms-conversion-rate.csv", show_col_types = FALSE)

# Recoded columns from numbers into descriptive labels using key at the bottom of
# the data CSV.

ms_data <- raw_df[-c(274:288) ,] |>
  mutate(Age = `Age (y)`) |>
  mutate(Schooling = `Schooling (y)`) |>
  mutate(Gender = recode(Gender,
                         '1' = "male",
                         '2' = "female")) |>
  mutate(Breastfeeding = recode(Breastfeeding,
                                '1' = "yes",
                                '2' = "no",
                                '3' = "unknown")) |>
  mutate(Varicella = recode(Varicella,
                            '1' = "positive",
                            '2' = "negative",
                            '3' = "unknown")) |>
  mutate(Initial_Symptoms = recode(`initial symptom`,
                                  '1' = "visual",
                                  '2' = "sensory",
                                  '3' = "motor",
                                  '4' = "other",
                                  '5' = "visual  and sensory",
                                  '6' = "visual  and motor",
                                  '7' = "visual  and other",
                                  '8' = "sensory  and motor",
                                  '9' = "sensory  and other",
                                  '10' = "motor  and  other",
                                  '11' = "visual,  sensory and motor",
                                  '12' = "visual, sensory  and other",
                                  '13' = "visual, motor and  other",
                                  '14' = "sensory,  motor and   other",
                                  '15' = "visual,sensory,motor and other")) |>
  mutate(Mono_Poly = recode(`Mono or polysymptomatic`,
                            '1' = "monosymptomatic",
                            '2' = "polysymptomatic",
                            '3' = "unknown")) |>
  mutate(Oligoclonal_Bands = recode(`Oligoclonal bands`,
                                   '0' = "negative",
                                   '1' = "positive",
                                   '2' = "unknown")) |>
  mutate(LLSSEP = recode(LLSSEP,
                        '0' = "negative",
                        '1' = "positive")) |>
  mutate(ULSSEP = recode(ULSSEP,
                        '0' = "negative",
                        '1' = "positive")) |>
  mutate(VEP = recode(VEP,
                      '0' = "negative",
                      '1' = "positive")) |>
  mutate(BAEP = recode(BAEP,
                       '0' = "negative",
                       '1' = "positive")) |>
  mutate(Periventricular_MRI = recode(`Periventricular MRI`,
                                      '0' = "negative",
                                      '1' = "positive")) |>
  mutate(Cortical_MRI = recode(`Cortical MRI`,
                                '0' = "negative",
                                '1' = "positive")) |>
  mutate(Infratentorial_MRI = recode(`Infratentorial MRI`,
                                      '0' = "negative",
                                      '1' = "positive")) |>
  mutate(Spinal_Cord_MRI = recode(`Spinal cord MRI`,
                                  '0' = "negative",
                                  '1' = "positive")) |> 
  mutate(group = recode(group,
                        '1' = "CDMS",
                        '2' = "Non-CDMS")) |>
  select(Patient, 
         Gender, 
         Age, 
         Schooling, 
         Breastfeeding, 
         Varicella,
         Initial_Symptoms,
         Mono_Poly,
         Oligoclonal_Bands,
         LLSSEP,
         ULSSEP,
         VEP,
         BAEP,
         Periventricular_MRI,
         Cortical_MRI,
         Infratentorial_MRI,
         Spinal_Cord_MRI,
         group) |> 
  drop_na()

# Removed rows with "unknown" for Oligoclonal Bands for clarity

x <- ms_data |>
  filter(Oligoclonal_Bands %in% c("positive", "negative"))

x <- x |>
  mutate(Oligoclonal_Bands = factor(Oligoclonal_Bands, levels = c("positive", "negative")))

```

```{r}
#| label: model

# Created brm model to compare group and Oligoclonal Bands. Used bernoulli
# family because group and Oligoclonal_Bands are binary variables. Used silent
# and refresh to get rid of extra output. Used seed to get replicable results.

fit_ob <- read_rds("fit_ob.rds")
```

## Mathematical Formula

$$ \text{logit}(P(group = 1)) = \beta_0 + \beta_1 \cdot Oligoclonal\_Bands $$


$$ P(group = 1) = \frac{1}{1 + \exp(-(\beta_0 + \beta_1 \cdot Oligoclonal\_Bands))} $$


## Outcomes of the Model

```{r}
#| message: false
#| warning: false

# Displayed results from the model in a readable format

tbl_regression(fit_ob)
```

## Posterior Predictive Check

```{r}
#| message: false
#| warning: false

# Displayed pattern of the model vs the observed data

pp_check(fit_ob)
```

As seen above, the model follows the general pattern of the actual data. 
